modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="anvilrecipes"
version="1.0.1"
displayName="Anvil Recipes"
logoFile="anvilrecipes.png"
authors="leod"
description='''
Implements "additionsmithing" (combining two items), "singlesmithing" (refining a single item) and "wildcardsmithing" (combining any item with a certain material) recipes for the Anvil.
'''